### ISSUE TITLE
Republishing this game

### ISSUE THREAD

**Issue by ogomez92** [caiobzen/2048-swiftui#3]
Hello!
I am a blind software developer and have made some modifications to your game to make it accessible.
Is your game on the appstore? Otherwise, is it OK if I publish it? What is the licnese on your icons?

Thanks.

**Comment by caiobzen** [comment]
Hi there, @ogomez92!
Thanks for making these modifications. It would be nice to have this game accessible to blind people!
It is not on the App Store as this was more of "me challenging myself" kind of project, so feel free to upload it and don't be afraid of keeping the icons because I drew them.

Thanks for reaching out and good luck with your game!

**Comment by ogomez92** [comment]
OK, thank you so much. I'll let you know when the game is done and
will also give you the code. It's more a matter of making things a bit
larger, adding information to voiceover about how many empty squares
there are, adding coordinate information to each cell, and letting the
user know which numbers appear in which cells. I'll let you know 🙂

**Comment by ogomez92** [comment]
As a blind software developer myself, SwiftUI is very nice because it
lets you do many things via code. With the old UIKit way, it was 1000
times harder.
If you want to keep in touch we can talk on Twitter or Discord or
whatever. I think you speak Spanish too?

Greetings.
